export type ServerType = {
    serverIds:number[]|null;
}

export const SERVER_TYPES=[
  "SEMINAR","EVENT","GENERAL","ANNOUNCEMENT","CLASSROOM","DISCUSSION","CLUB",
  "DEPARTMENTAL","STUDENT_BODY","SUPPORT","RESEARCH","WORKSHOP","EXAM",
  "ALUMNI","FACULTY","ADMINISTRATION"
];

export const USER_TYPES=[
    "STUDENT","ASSISTANT_PROFR","ASSOCIATE_PROFR","PROFR","HOD","REGISTRAR","CLERKS",
    "COORDINATOR","PRINCIPAL","DEAN","DIRECTOR","LIBRARIAN","LAB_ASSISTANT",
    "SECURITY_STAFF","JANITORIAL_STAFF","TRANSPORT_STAFF","CAFETERIA_STAFF",
    "LAB_TECHNICIANS","IT_STAFF","GUEST","ALUMINI","ADMIN"
];

export const DEPARTMENT_TYPE=[
    "AE","AD","AI","BT","CH","CV","CS","CI","CY","EE",
    "EC","EI","ET","IM","IS","ME","MD","AT"
];

export const YEARS = [ 1, 2, 3, 4];
export const SEMESTERS = [ 1, 2, 3, 4, 5, 6, 7, 8] ;
export const SECTIONS = [ "A", "B", "C", "D"];

export const TIER2 = [
  "ASSISTANT_PROFR", "ASSOCIATE_PROFR", "PROFR", "HOD","REGISTRAR", "CLERKS", "COORDINATOR"
];
export const TIER1 = [
  "PRINCIPAL", "DEAN", "DIRECTOR", "LIBRARIAN", "LAB_ASSISTANT", "SECURITY_STAFF",
  "JANITORIAL_STAFF", "TRANSPORT_STAFF", "CAFETERIA_STAFF", "LAB_TECHNICIANS", "IT_STAFF"
];
export const TIER0 = [
  "GUEST", "ALUMNI", "ADMIN"
];